-- Migration: 001_baseline_ymemo_table.sql
-- Description: Create baseline ymemo table (idempotent for universal deployment)
-- Author: system
-- Created: 2025-01-02
-- Status: EXECUTABLE (works on fresh or existing databases)

-- Create ymemo table matching current production schema
-- Uses IF NOT EXISTS to be safe for existing databases
CREATE TABLE IF NOT EXISTS public.ymemo (
  id integer generated by default as identity not null,
  name text null,
  duration numeric null,
  transcription text null,
  created_at timestamp with time zone not null default now(),
  audio_file_path text null,
  constraint ymemo_pkey primary key (id)
) TABLESPACE pg_default;

-- Add any missing indexes that should exist on the baseline table
-- (Currently no additional indexes defined for ymemo table)

-- This migration creates the foundational ymemo table structure.
-- It uses CREATE TABLE IF NOT EXISTS to be safe on databases where
-- the table already exists, making it suitable for:
-- - Fresh database deployments (dev/staging/test environments)
-- - Re-deployment scenarios
-- - Schema reconstruction
-- - Environment consistency
