-- Migration: 002_create_persona_table.sql
-- Description: Add persona management functionality
-- Author: system
-- Created: 2025-01-02
-- Dependencies: 001_baseline_ymemo_table.sql

-- Create simplified persona table following ymemo table patterns
CREATE TABLE public.ymemo_persona (
  id integer generated by default as identity not null,
  name text not null,
  description text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint ymemo_persona_pkey primary key (id),
  constraint ymemo_persona_name_check check (length(trim(name)) > 0)
) TABLESPACE pg_default;

-- Create indexes for performance
CREATE INDEX idx_ymemo_persona_created_at ON public.ymemo_persona (created_at DESC);

-- Add trigger for updated_at auto-update
CREATE OR REPLACE FUNCTION update_ymemo_persona_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_ymemo_persona_updated_at
    BEFORE UPDATE ON public.ymemo_persona
    FOR EACH ROW
    EXECUTE FUNCTION update_ymemo_persona_updated_at();
